### ISSUE TITLE
Warn user if she's about to send an email to no-one.

### ISSUE THREAD

**Issue by JoKeyser** [Fperdreau/jcm#7]
Hi Florian, it's just more of a feature request, really:

In the mailing interface, you can manage not to send anything, if you fail to click on the "big plus" to actually add the recipients. This may go unnoticed, but I think the user should be warned that nothing has been sent.

**Comment by JoKeyser** [comment]
PS: I witnessed this, so it's not just a hypothetical case :).

**Comment by Fperdreau** [comment]
Hi Johannes,
Thanks for the feedback. I added a warning message to inform the user that at least one recipient must be added by clicking on the big "+" button.
