### ISSUE TITLE
Idea for feature: Option to set messages to everyone as News.

### ISSUE THREAD

**Issue by JoKeyser** [Fperdreau/jcm#9]
Hi, I've noticed that people tend to send news-worthy items only as messages to everyone. Presumably they want to ensure it's sent immediately rather than sent later in the weekly digest.
Unfortunately however, it leads to a very outdated (or empty) News section...

One idea to solve this technically rather than asking people to change is this:
* Add an option "also publish as news" next to the Email Tool, default is No.
* If you select `All` from the list of Email recipients, change that default to Yes.

**Comment by Fperdreau** [comment]
Thank you for the idea. This feature has been added to the future release of JCM.
